In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df = pd.read_csv(r"C:\Users\bittu\OneDrive\Documents\homepr.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
import math
df.bedrooms.median()

4.0

In [11]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
model = linear_model.LinearRegression()
model.fit(df.drop('price', axis = 'columns') , df.price)

LinearRegression()

In [21]:
model.predict([[3000,3,40]])

C:\Users\bittu\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [22]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [24]:
model.intercept_

221323.00186540408

In [25]:
112.06244*3000+23388.8800*3+-3231.71790*40+221323.001865

498408.245865

In [26]:
model.predict([[2500,4,5]])

C:\Users\bittu\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])